// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs4rKs_jEEhng80HS2MFyqnxpRGkF_BJ8',
    appId: '1:797312516180:web:df192564c07ae3ee54adc1',
    messagingSenderId: '797312516180',
    projectId: 'httpcrud-a8bd0',
    authDomain: 'httpcrud-a8bd0.firebaseapp.com',
    storageBucket: 'httpcrud-a8bd0.appspot.com',
    measurementId: 'G-8PJQD4RW75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5alx8UEwj5Fs-EDvG0AOGpzsSNmH2Jtk',
    appId: '1:797312516180:android:cb1f5232b8527f8754adc1',
    messagingSenderId: '797312516180',
    projectId: 'httpcrud-a8bd0',
    storageBucket: 'httpcrud-a8bd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-UlcvP9RE-BzuQjWNvgMSNWvwyvisoc',
    appId: '1:797312516180:ios:7e7ddca0bcb4b12254adc1',
    messagingSenderId: '797312516180',
    projectId: 'httpcrud-a8bd0',
    storageBucket: 'httpcrud-a8bd0.appspot.com',
    iosBundleId: 'com.example.httpCrudUsingProviderAndAppStructure',
  );
}
